# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Hamlet Batista
tagline:             'Bringing agile to SEO'
description:         'SEO results in 6 weeks, not 6 months!'
url:                 https://www.ranksense.com
baseurl:             '/exam'
paginate:            5

# About/contact
author:
  name:              Hamlet Batista
  url:               https://twitter.com/hamletbatista
  email:             hamletb@ranksense.com

# Custom vars
version:             1.0.0
